sourcecred/cred

- transfers.json
I defined a simple format for the transfers, which just gives the
basic necessary info (who, how much, when) along with arbitrary
references. I linked to the open collective payout and the discourse
payout request in the references.
No code yet consumes this information.
cc @s-ben
> Record a transfer from @s-ben to @protocol

- projects/combined.json
- projects/github.json
The work that goes into this repository should count too. :)
Test plan: Run the update script, verify that it loads without issue.
> Track `sourcecred/cred` for cred purposes

- transfers.json
> Record a transfer from s-ben to protocol

- weights.json
See the post here:
https://discourse.sourcecred.io/t/community-call-2-notes-recording/327
> Give a 4x weight to Community Call notes

- transfers.json
Thanks to @pk-controller for discussions around our new transfer format.
> Propose a transfer from @s_ben to @protocol

- projects/combined.json
Continues from #8
Maps @vsoch to her new Discourse account.
> Add identity for vsoch

- projects/combined.json
- projects/github.json
Holding @vsoch's work on example actions. Should track that :]
> Add sourcecred/sourcecred-action repository

- project.json
cc @hammadj @miyazono
Test plan:
Updating the instance should collapse to their respective identity nodes.
> Add hammadj and miyazono identities

- docs/CNAME
Attempt to fix https://github.com/sourcecred/sourcecred/issues/1761.
Paired with @Beanow
> Create experimental CNAME

- transfers.json
A transfer of 6k grain.
Review plan: Approval by @s_ben (to confirm receipt of payment) and from
@Beanow (to confirm that the format is correct).
> Add transfer from s_ben to amico

- project.json
Adds @topocount to the identities in project.json
> Add Topocount to identities

- .github/workflows/generate-instance.yml
This time we explicitly remove the old symlinks and then copy the data files in.
Test plan: Merge this and see if the build works.
cc @hammadj
> Another attempt to fix deploy

- yarn.lock
> Fix the lock file

- package.json
- yarn.lock
Notably, this renames the `sourcecred admin` command to `sourcecred
serve`.
> Upgrade to SC beta 10

- package.json
- yarn.lock
Most notably, this fixes bugs in the dependency minted cred calculation.
> Upgrade to beta-14

- package.json
- yarn.lock
Introduces Dandelion's fix for Discourse 520 errors
> Bump SourceCred to v0.7.3

- .github/dependabot.yml
This will help us keep our instance up to date with the most
recent sourcecred release and github actions.
test plan: validated the file here:
https://dependabot.com/docs/config-file/validator/
>  Set up dependabot

- data/ledger.json
Activating Santigs, Marcvi1a, Felix
> Activating Identities Batch 1

- data/ledger.json
Crisog
Macgyver
Merging "befitsandpiper"
> Activating Identities Batch 2

- data/ledger.json
To Panchomiguel:
https://etherscan.io/tx/0xbe9e22226ed6c5d0426da12b8359ea5029f5baa2bb3697e3d2b59406cd9ddf4d
> Grain Sale 21

- sourcecred.json
Related to issue # 2510 on the main sourcecred repo:
https://github.com/sourcecred/sourcecred/issues/2510
> Reorder plugins for better weightconfig layout

- data/ledger.json
This is my first go at fulfilling grain activation requests.
This batch PR activates the following:
OttoZastrow#5796
metaverde#2503
magwalk#8115
saintmedusa#0546
prose11#7778
yetifree#4460
monstrosity#5714
And merges into the above:
github/saintmedusa
discourse/prose11
discourse/otto
I double checked the merges, since those are difficult to reverse.
> Batch Merge and Activate Identities

- data/ledger.json
https://etherscan.io/tx/0x7415a7a4a8b3b99ff98ab0394f8d4b042a25828ad3ff2d168295fdeedbe85b27
> Grain Sale 42 Thena

- data/ledger.json
For context, see this [post].
[post]: https://discourse.sourcecred.io/t/adding-a-grain-salary-cap/925/16
> Re-activate decentralion's grain account

- data/ledger.json
joiecousins: https://etherscan.io/tx/0xb46525d0f25baf02c5a63a19228dfd25572cc33b553f45e9f55f90f99dfd148b
> Grain Sale 44

- data/ledger.json
Activated discord/New_World_Sinnian#0295 and renamed to Jojo
> Activate Jojo

- data/ledger.json
2500g Personal Assistant transfer for January
> LB to Joie January Grain Transfer

- data/ledger.json
kurafire: https://etherscan.io/tx/0x70ae012aa4fa001b809f124e6b08c626178a60c4869e1383f609b0dddbb9619d
> Grain Sale 46.1

- data/ledger.json
Merge BrianBelhumeur and BrianBelhumeur-discourse identities
> Merge identities for Brian Belhumeur

- config/dependencies.json
We owe DeepWork some cred! The agreement was vague, and didn't include a description of how much cred or how that cred would be accounted for... Here's 20% of the total cred minted as bonus cred for the week of the hypersprint. I did saturday to saturday so that it would correctly bound the start time of that epoch.
1. checkout gh-pages branch
1. hand remove the last grain distribution from the ledger
1. yarn sourcecred score
1. yarn sourcecred credrank
2. yarn grain
|          name          |    total    |     %     |
| ---------------------- | ----------- | --------- |
|         Thena          |  3,316.141  |  13.26%   |
|        KuraFire        |  1,976.349  |   7.91%   |
|       topocount        |  1,912.761  |   7.65%   |
|      panchomiguel      |  1,662.521  |   6.65%   |
| …
> Add DeepWork cred dependency

- package.json
- yarn.lock
bumped version and ran `yarn`
1. checkout gh-pages branch
2. bump version
3. `yarn`
4. `yarn serve`
5. verify explorer home loads
> bump sourcecred to 0.8.0

- data/ledger.json
https://observablehq.com/@blueridger/sourcecred-ledger-viewer?branchUrl=https://github.com/sourcecred/cred/tree/merges
> Batch merge and activate

- .github/workflows/distribute-grain.yml
Description language should to be formatted slightly differently now that it is a commit body instead of a PR description.
> Clean up commit body

- .github/workflows/generate-instance.yml
> Change master branch to main in gh action

- config/personalAttributions.json
As passed by Core today: https://roamresearch.com/#/app/SourceCred/page/fvwAesKMx
tested with `yarn sourcecred credrank -s -d`
> Personal Attributions: Thena>Jojo, Protocol Labs Sponsorships

- data/ledger.json
> Merge FredDog

- config/personalAttributions.json
This is required because our DistributeGrain workflow only commits ledger changes, not config updates (which I will also fix).
-----
> Fix broken build with updated personalAttributions

- config/plugins/sourcecred/initiatives/config.json
Not totally sure what this is for, but best to update it anyways!
-----
> Update to main in initiatives plugin

- .github/pull_request_template.md
This changes the ledger viewer URL to be an updated improved version of the ledger viewer.
It also add the two spreadsheets that commonly need to be cross-referenced be reviewers.
> Improve reviewer resources in PR template

- config/personalAttributions.json
Protip: enable "hide whitespace" under the settings gear when reviewing the file changes :wink:
> Kevin ends PL sponsorship

- data/ledger.json
> Activiate Zevi's Wallet

- data/ledger.json
Discussed/approved out of band.
-----
> Private grain sale from Joie to wchargin

- data/ledger.json
Bought 2k grain from Yaz ($1 per grain) on Jan 25th,
https://etherscan.io/tx/0xc7e1effdd1b6a4c733c6829940c3a016409763e270bfca077e78057a9630346e
-----
> s-ben buying 2,000 grain from saintmedusa
