sourcecred/cred

- weights.json
This is a small experiment in having something like [Cred Bounties][1]
before we've actually implemented the [Initiatives Plugin][2].
Basically, we're giving a higher weight to a few initiatives:
- Produce the SourceCred Podcast: Shipped the podcast!
- Discourse Reference Detection: Recently completed.
- Champions & Heroes: An exciting contribution. :)
- Initiatives Plugin: Nice progress so far.
The weight choices are moderate, so it doesn't have a _huge_ effect on
cred--we'll hold off on big effects for after the initiatives plugin and
cred bounties both land. But this is a nice way to recognize some
exciting progress so far.
[1]: https://discourse.sourcecred.io/t/enable-cred-bounties/257
[2]: https://discourse.sourcecred.io/t/write-the-initiatives-plugin/269
> Prototype "cred bounties" via manual weights

- weights.json
This update is needed as of sourcecred/sourcecred#1558. I didn't make
any changes to the weights themselves. As discussed in the review there,
the weights semantics changed in some edge cases; happily, none of those
edge cases were present in our weights.
Test plan: I've re-computed cred using the new weights (built against
sourcecred master) and verified that the weights are set correctly in
the UI.
> convert weights to 0.2.0 format

- distributionHistory.json
Since the grain distribution tracker is not yet aware of the identities
plugin, now that we've created an identity for amico (cf #18), we should
rewrite history so that the past distributions to amico are recorded
properly.
Test plan: `git grep sabba` returns no hits.
> Change distribution history to account for rename

- project.json
Assumes #22 will be merged.
Using the anonymous API, an apiUsername is no longer needed.
Test plan:
Locally running the update script updates the Discourse server correctly.
> Upgrade project to v0.4.0 format

- project.json
Assumes #22 is merged.
The repository itself was renamed. See https://github.com/sourcecred/github-workflow-examples/pull/42
> Rename sourcecred-action to github-workflow-examples

- project.json
- update.sh
Assumes #22 and #23 are merged.
This updates the project file mainly. Which means we now require
the environment variable `SOURCECRED_INITIATIVES_DIRECTORY` is set
and a valid directory. To make sure of this an empty directory is
added, and the environment variable is exported.
Test plan:
Updating the instance should include "[  GO  ] initiatives" and "[ DONE ] initiatives" in it's progress indicator. This indicates both the project file is correctly updated and `SOURCECRED_INITIATIVES_DIRECTORY` is set and valid.
> Set up initiatives for the project

- initiatives/2020-02-credcon-adoption-meeting.json
- initiatives/2020-02-credcon-buidl-talk.json
- initiatives/2020-02-credcon-car.json
- initiatives/2020-02-credcon-food.json
- initiatives/2020-02-credcon-hackathon.json
- initiatives/2020-02-credcon-lodging.json
- initiatives/2020-02-credcon-party.json
- initiatives/2020-02-credcon-sustain-web3-talk.json
- initiatives/2020-02-credcon.json
- initiatives/2020-02-partner-maker.json
- initiatives/2020-02-partner-metagame.json
Depends on #26
_Edit: rather than letting this stall for too long, let's improve on this with follow ups.
Have a look at #29 for info on how to go from here._
This is ~~a preview~~ a first iteration, as it's in need of another weighting round.
Still missing from this, but identified at the team call:
- CredCon: video interviews (need a user account for zak)
- CredCon: CredRank prototype (have not decided fibonacci weight)
- CredCon: Discord prototype (have not decided fibonacci weight)
- Evan's explainer (have not decided fibonacci weight)
Also great improvements to make from here:
- Adding contributions and linking that to contributors (see #30)
Good but not as critical:
- Making the timestamps more accurate
_Edit: see https://github.com/sourcecred/cred/pull/27#issuecomment-610607504 …
> Add first batch of CredCon and Partner initiatives

- project.json
Hadn't yet mapped @burrrata's identity :open_mouth:
Test plan: loaded with updated `project.json` and verified the explorer includes the merged identity.
> Add identity for burrrata

- initiatives/2020-05-initiatives-editor-raid.json
In the spirit of dog-fooding, creating this initiative to keep track of contributions for RaidGuilds work on the Initiatives Editor. The distribution of funds within the Raid will happen based on resulting cred scores from this initiative.
Paired with: @decentralion
> Create initiative for Initiatives Editor Raid

- .github/workflows/generate-instance.yml
This commit will probably produce a broken deployment with broken symlinks. But I want to give it a try because it'd be really convenient if this somehow Just Worked.
Test plan: Merge, and see if the resultant build works. Dubious but possible.
cc @hammadj
> Try to deploy without touching symlinks

- config/plugins/sourcecred/github/config.json
New repo to be used as a starting point for users of SourceCred: https://github.com/sourcecred/template-instance
> Add template instance to list of repos

- .github/workflows/distribute-grain.yml
Summary:
This patch adds a workflow to compute grain distributions from a clean
cache on a weekly schedule, deploying the results to GitHub Pages.
Paired with @topocount.
Paired with @wchargin.
Test Plan:
Pushed to a `graintest-*` branch, spawning a test run that succeeded but
did not push to GitHub Pages (as intended):
<https://github.com/sourcecred/cred/runs/936349886>
The actual GitHub Pages push thus hasn’t been tested yet.
> An action for distributing Grain

- .github/workflows/generate-instance.yml
This changes the cred computation to occurs every 24 hours at 0:00 UTC. This change will be verified once merged.
> Change cred calculation interval from 6 to 24 hours

- README.md
- package.json
Usage:
`yarn go` to reload all the data
`yarn go --no-load` to regenerate scores without loading data
Also updated README.
> Add `yarn go` command

- package.json
This puts `yarn serve` back in, which was removed in #138.
It's convenient to be able to turn on the server (e.g. to inspect the
ledger) without needing to reload everything.
> Re-add the yarn serve command

- data/ledger.json
LB transfers Joie 2500g every month. 
this covers November
> November LB to Joie Transfer

- config/dependencies.json
- config/grain.json
This PR has two commits which change our Cred and Grain configuration:
1. We no longer mint Cred for the @sourcecred account. We did that as a way of providing Grain funding for the SC treasury, but we're going to use a different mechanism for that going forward.
2. We boost the weekly Grain issuance back up to 25k. This is where it was before the holiday bonus. I've switched the payout to be 20k to RECENT and 5k for BALANCED.
> Update Cred/Grain configuration

- .github/workflows/distribute-grain.yml
This change will cause grain distributions to automatically commit to master, instead of setting up a PR.
This is justified because:
1. There is a strong need for better reliability in payout timeliness
2. The risk of attacks/bugs is low, and ultimately fixable via ledger hand-editing.
I ran it with success in another branch:
https://github.com/sourcecred/cred/commits/grain-trigger-auto
1. Will it work in the `master` branch even though master is a protected branch? (Are the permissions prepared?)
> Auto-commit Grain Distributions to main

- .github/workflows/distribute-grain.yml
Reverts sourcecred/cred#209
Pushing directly to master is blocked, as it should be. We are going to take a different approach to auto-grain.
> Revert "Auto-commit Grain Distributions to main"

- .github/workflows/generate-instance.yml
I want to be able to locally serve the gh-pages branch, so that I can play with prod scores/graphs without having to run `load`. Currently, this is really annoying to do: you have to copy files across branches since the gh-pages branch is missing the package.json file. So this PR copies the package file into the deployed site so that it is present in the generate gh-pages branch.
I chose not to copy the yarn.lock file as well, and it worked without. Not sure if I should also include the yarn.lock file or if it's ok without.
1. Pushed [a test branch](https://github.com/sourcecred/cred/tree/gh-pages-serve-test) to set off a deployment to [a test deployment branch](https://github.com/sourcecred/cred/tree/gh-pages-test)
2. Went to https://github.com/sourcecred/cred/settings and configured …
> Add package.json to gh-pages branch so you can checkout and serve

- .github/workflows/distribute-grain.yml
Switching the default reviewer to @panchomiguel, as he is treasurer.
> Change default grain distribution reviewer

- .github/workflows/distribute-grain.yml
Grain distributions should be committed directly to avoid merge
conflicts and ensure reliably-timed distributions for the community.
The action will utilize a configured `ADMIN_TOKEN` secret in the github
repo to ensure the action has permissions to commit directly to master
on scheduled runs. The user of the token must have admin permissions in
the repo and the token utilized must have permissions to push to public
repositories:
ensured committing to a protected branch worked in a forked
topocount/cred repo using a simple autocommit action
> Commit Grain Distributions Directly: attempt 2

- .github/workflows/distribute-grain.yml
This enables grain distributions to be triggered manually from the UI, but only by contributors
with write access.
> Add workflow-dispatch for grain distributions

- .github/workflows/distribute-grain.yml
- .github/workflows/generate-instance.yml
see https://github.com/sourcecred/template-instance/pull/72 for reference.
This prevents any latent bugs. if we ever decide to start generating cred from private repos (not likely), but more importantly, it also bring us inline with the template instance and will allow for less confusion when others are looking at our work for reference.
test plan: the workflow should pass on merge
> Update Workflows to use our Github Secret

- .github/workflows/generate-instance.yml
This will allow `graph` CLI to be run from a fresh clone, making a lot of weights and code experimentation easier.
-----
> Add cache to actions deployment (experiment)

- .gitignore
Based on this doc: https://git-scm.com/docs/gitignore
Miguel saw one appear in root as well as /config, so I added ** to the matcher. I think that's right?
> Add DS_STORE to git ignore

- config/pluginBudgets.json
Tested by running `yarn sourcecred credrank` on the gh-pages branch data
> June 2021 break - plugin budgets config

- .github/workflows/distribute-grain.yml
This is important because credrank updates some config files, such as personalAttributions.json
-----
> Commit /config during DistributeGrain workflow

- .github/workflows/generate-instance.yml
I used the gh-pages branch as a test instance A LOT. This will help keep my workspace clean as I do so. Will be tested after merge.
> Add .gitignore to gh-pages deployment

- config/plugins/sourcecred/initiatives/initiatives/2020-02-partner-metagame.json
- config/plugins/sourcecred/initiatives/initiatives/2020-05-initiatives-editor-raid.json
Hammad changed his username on github and it broke his references in our
initiatives. This change fixes them.
test plan:
`yarn sourcecred graph` runs without any errors logged from the
initiatives plugin
> Convert github hammadj references to META-DREAMER

- config/personalAttributions.json
The funding agreement I just signed contains the following clause:
> WHEREAS, Protocol Labs provided open source development grants to certain individuals to fund their open source contributions to the Project, and all of the grants have expired on their own terms; 
So we can count the sponsorships as done, which is great because they were a semantic misuse of personal attributions.
-----
> End all PL sponsorships

- .github/workflows/generate-instance.yml
We are getting a consistent 404 that might be affecting cred scores. This will wipe the actions cache. From what I can tell by the error, this will likely fix it. https://github.com/sourcecred/cred/runs/4437776446?check_suite_focus=true
-----
> Wipe actions cache
